#ifndef APPLICATION_ACTION_HANDLER_ABI_BRIDGE_HPP_
#define APPLICATION_ACTION_HANDLER_ABI_BRIDGE_HPP_

auto RegisterActionHandlerCoreDelegate() -> void;

#endif  // APPLICATION_ACTION_HANDLER_ABI_BRIDGE_HPP_
